# Generated by Django 4.0.5 on 2022-07-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('pname', models.CharField(max_length=122)),
                ('occupation', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('dob', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('others', 'others')], default='male', max_length=122)),
            ],
        ),
    ]
