# Generated by Django 4.0.5 on 2022-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_admission_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='name',
            new_name='yname',
        ),
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(choices=[('others', 'others'), ('female', 'female'), ('male', 'male')], default='male', max_length=122),
        ),
    ]
