# Generated by Django 4.0.5 on 2022-08-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_admission_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='gender',
        ),
    ]
