# Generated by Django 4.0.5 on 2022-08-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_admission_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admission',
            new_name='admission1',
        ),
    ]
