# Generated by Django 4.0.5 on 2022-08-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_admission_admission1'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y2name', models.CharField(max_length=122)),
                ('p2name', models.CharField(max_length=122)),
                ('address2', models.CharField(max_length=122)),
                ('phone2', models.CharField(max_length=122)),
                ('rolln', models.CharField(max_length=122)),
                ('cardn', models.CharField(max_length=122)),
                ('expm', models.CharField(max_length=122)),
                ('pay', models.FloatField(max_length=122)),
            ],
        ),
    ]
