# Generated by Django 4.0.5 on 2022-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_payment1'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('passw', models.CharField(max_length=122)),
                ('time', models.CharField(max_length=122)),
                ('subj', models.CharField(max_length=122)),
                ('teacher', models.CharField(max_length=122)),
            ],
        ),
    ]
