# Generated by Django 4.0.5 on 2022-08-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_admin1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin1',
            name='class_id',
            field=models.CharField(max_length=122),
        ),
    ]
