# Generated by Django 4.0.5 on 2022-08-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_admin1_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin1',
            old_name='teacher',
            new_name='class1',
        ),
    ]
