# Generated by Django 4.0.5 on 2022-08-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_teacher_admin1_class1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin1',
            old_name='class1',
            new_name='Grade',
        ),
    ]
