# Generated by Django 4.0.5 on 2022-09-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_class1_admin1_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin1',
            old_name='Grade',
            new_name='Link',
        ),
    ]
