# Generated by Django 4.0.5 on 2022-09-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_grade_admin1_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin1',
            old_name='Link',
            new_name='link',
        ),
    ]
