# Generated by Django 4.0.5 on 2022-09-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_link_admin1_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin1',
            old_name='subj',
            new_name='grade',
        ),
    ]
