# Generated by Django 4.0.5 on 2022-09-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_payment1_rolln'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment1',
            old_name='phone2',
            new_name='phone3',
        ),
    ]
