# Generated by Django 4.0.5 on 2022-09-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_phone2_payment1_phone3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment1',
            name='phone3',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
